version: '3'
services:
  db:
    image: postgres
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/code
      - static_vol:/code/static
    ports:
      - "8000:8000"
    depends_on:
      - frontend
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/opt/app
      - opt/app/node_modules

volumes:
  static_vol:
    