# Generated by Django 3.1.7 on 2021-03-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_auto_20210328_1045"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="pay_for_transport",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="offer",
            name="ship_documents_to_agency",
            field=models.DateField(blank=True, null=True),
        ),
    ]
